title: oschvr.com
url: https://oschvr.com
description: "a blog about development, networks, stacks, artificial intelligence, spatial computing, cryptography, blockchains,  startups, business, politics, finance, economics and mexico."
show_downloads: true
google_analytics: UA-73304631-6
theme: jekyll-theme-hacker
plugins: [jekyll-paginate-v2, jekyll-sitemap, jemoji]
twitter:
  username: oschvr
pagination:
  enabled: true
  debug: true
  collection: 'articles'
  per_page: 9
  permalink: /posts/:num/
  title: ':title - page :num'
  limit: 0
  sort_field: date
  sort_reverse: true
  #category: /posts/:category
  #tag: /posts/:tags
  #locale: /posts/:locale
autopages:
  enabled: false
collections: 
  articles:
    output: true
    permalink: /posts/:path
  pages:
    output: true
    permalink: /pages/:path
  projects:
    output: true
    permalink: /projects/:path
defaults:
  scope:
    path: ""
    type: "articles"
  values:
    layout: "post"
  scope:
    path: ""
    type: "pages"
  values:
    layout: "page"
  scope:
    path: ""
    type: "projects"
  values:
    layout: "post"